### ISSUE TITLE
Score increments when message app is clicked

### ISSUE THREAD

**Issue by uifd132** [uifd132/GirlFriendClicker#2]
opening the messaging app increments score by 1. this is a bug

**Comment by moistsaxophone** [comment]
I'll take a look at this in the morning

**Comment by moistsaxophone** [comment]
So it looks like this is only happening when you click on a part of the button that overlaps with the message button hitbox, I'll try to fix that right now because it will prevent us from placing other buttons where apps are on the screen in the future

**Comment by moistsaxophone** [comment]
Fixed by adding a variable that counts how many times you've clicked in an app called clickCount
